### ISSUE TITLE
Relate algorithm Issue Summary

### ISSUE THREAD

**Issue by dr-jts** [libgeos/geos#1060]
A summary collecting all issues filed about the topological predicates (the Relate algorithm).

## Incorrect Result for GeometryCollection
* #1033
* #1027 
* #1022 
* #1011 
* #983 
* #982 
* #981 

### See Also
* [PostGIS 4749: Improve behaviour of spatial predicates with GeometryCollection inputs](https://trac.osgeo.org/postgis/ticket/4749)
* [PostGIS 5777: st_intersects() throws exception when using geometrycollection as first argument](https://trac.osgeo.org/postgis/ticket/5777)
* https://github.com/locationtech/jts/issues/539
* https://gis.stackexchange.com/questions/283362/postgis-error-relate-operation-called-with-a-lwgeomcollection-type

## Zero-length LineString handling
* https://github.com/locationtech/jts/issues/1050
* https://github.com/locationtech/jts/issues/345
* https://github.com/locationtech/jts/issues/1079

## Incorrect Result due to Robustness/Rounding error
* #1064 (issue due to noding of lines - not clear if this can be fixed)
* #1053
* #968
* #933
* #740

## TopologyException
* #766
* #1026 
* #1069
* https://github.com/locationtech/jts/issues/1051
* https://trac.osgeo.org/postgis/ticket/5362
* https://trac.osgeo.org/postgis/ticket/5583
* https://gis.stackexchange.com/questions/484691/topologyexception-side-location-conflict-while-intersects-on-valid-polygons

## Performance
* #1024
* [GEOS-708](https://trac.osgeo.org/geos/ticket/708) / [PostGIS 2975](https://trac.osgeo.org/postgis/ticket/2975) - excessive line noding causes OOM error

**Comment by dr-jts** [comment]
Fixed by RelateNG port: https://github.com/libgeos/geos/commit/d963c0f0becb83979f732e940f2f8eb80584a5a8

**Comment by tjwebb** [comment]
so... when will this be available in APT? Still getting 3.11 containing these bugs

**Comment by pramsey** [comment]
See https://lists.osgeo.org/pipermail/geos-devel/2025-March/011103.html
